name: tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  testing:
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup pdm to Python ${{ matrix.python-version }}
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pdm sync --dev -G test -G dev

      - name: Tests with tox
        env:
          COVERAGE_FILE: ".coverage.${{ matrix.python-version }}.${{ matrix.os }}"
        run: |
          pdm run tox --version
          pdm run tox --develop -r -e py

      - name: Store coverage file
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-${{ matrix.os }}
          path: .coverage.${{ matrix.python-version }}.${{ matrix.os }}

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: testing
    permissions:
      # Gives the action the necessary permissions
      # for publishing new comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        id: download
        with:
          pattern: coverage-*-*
          merge-multiple: true

      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_DATA_BRANCH: python-coverage
          COMMENT_ARTIFACT_NAME: python-coverage
          COMMENT_FILENAME: python-coverage.txt
          MERGE_COVERAGE_FILES: true

      - name: Store Pull Request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage
          path: python-coverage.txt
